### ISSUE TITLE
Mesure | Passage de l'identifiant de compteur en propriété optionnelle

### ISSUE THREAD

**Issue by vdieulesaint** [etalab/schema-comptage-mobilites#3]
En tant que fournisseur de données de comptage de mobilité, je souhaite que l'identifiant de compteur (propriété counter_id) présent dans la mesure (measures.csv) devienne optionnel afin de supporter un site de comptage dépourvu de solution de comptage physique.
Cela permettrait d'adresser et de produire des données pour les cas d'usage suivant par exemple :
- comptage manuel (contre-comptage) réalisé par une association
- site de comptage virtuel 
- données de comptage importées sur la plateforme du fournisseur sans référence vers un système de comptage

**Comment by Miryad3108** [comment]
Le champ est passé en optionnel : https://github.com/etalab/schema-comptage-mobilites/releases/tag/v0.2.4. Merci @vdieulesaint pour ta contribution.
